/**
 * Shared domain types.
 *
 * Kept in its own module so both the UI and the persistence layer can import
 * them without creating a circular dependency.
 */

/**
 * Single source of truth for the displayed version: injected at build time
 * from package.json (see vite.config.ts), so the About tab can never drift
 * from the shipped manifests.
 */
export const APP_VERSION: string = import.meta.env.VITE_APP_VERSION ?? "0.0.0";

/**
 * App color themes. Every id maps 1:1 to a COMPLETE [data-theme] block in
 * src/styles.css (all tokens incl. hover/row) — adding a theme means adding
 * both a CSS block and a THEME_LIST entry below.
 */
export type Theme =
  | "dark"
  | "light"
  | "slate"
  | "amoled"
  | "vibe"
  | "one-dark-pro"
  | "dracula"
  | "github-dark"
  | "github-light"
  | "tokyo-night"
  | "monokai-pro"
  | "solarized-dark"
  | "solarized-light"
  | "nord"
  | "gruvbox"
  | "catppuccin";

export interface Conversation {
  id: string;
  title: string;
  /** Unix seconds of the last stored message; the sidebar renders "41s/2h/3d" from it. */
  updatedAt: number;
  pinned?: boolean;
}

/** Humanizes an age in seconds as 41sec / 5min / 2h / 3d / 1y (UI caps style). */
export function ageLabel(updatedAtUnix: number, nowUnix: number): string {
  if (!updatedAtUnix) return "";
  const s = Math.max(0, nowUnix - updatedAtUnix);
  if (s < 60) return `${s}sec`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}min`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h`;
  const d = Math.floor(h / 24);
  if (d < 365) return `${d}d`;
  return `${Math.floor(d / 365)}y`;
}

/**
 * Per-project command permission:
 * `bypass` runs commands without asking, `ask` always prompts,
 * `default` inherits the global setting.
 */
export type PermMode = "bypass" | "default" | "ask";

export interface Project {
  name: string;
  path: string;
  conversations: Conversation[];
  /** Command permission mode; absent on older data means `default`. */
  permMode?: PermMode;
}

export type ViewKind =
  | "chat"
  | "new"
  | "history"
  | "tasks"
  | "units"
  | "ssh-logs"
  | "ssh-terminal"
  | "ssh-files";

/** Which Units sub-collection the Units page shows (segmented switcher). */
export type UnitsTab = "servers" | "keys" | "scripts" | "proxies";

/* ---------- SSH Client mode ---------- */

/**
 * The two app modes. Agent is the coding-assistant workspace (chats,
 * projects, settings); SSH Client swaps the sidebar and the main view to
 * server units and their connection log. Generation runs live in Rust and
 * keep streaming across a mode switch — nothing is cancelled by switching.
 */
export type AppMode = "agent" | "ssh";

/**
 * A saved SSH server unit. Secrets live in SQLite AES-256-GCM encrypted
 * (vault.rs); listings from Rust carry blank password/privateKey — the UI
 * only sends plaintext when saving.
 */
export interface SshServer {
  id: string;
  name: string;
  host: string;
  port: number;
  username: string;
  /**
   * Preferred method for the UI, but BOTH sources may be configured at once
   * (Termius-style): a password AND a saved credential key — the connector
   * tries the key first, then falls back to the password. "key" (inline
   * private key paste) is legacy and no longer offered by the forms.
   */
  auth: "password" | "key" | "cred";
  /** Plaintext only when saving; "" in listings; "-" on the wire = remove stored password. */
  password: string;
  /** Legacy inline key — no longer accepted; the body lives in Credentials. */
  private_key: string;
  /** ssh_keys row id of the linked credential ("" = none). */
  key_id: string;
  /** Pinned host-key fingerprint ("SHA256:…"); "" = not seen yet. */
  host_key: string;
  /** True in listings when a password is stored (secret never crosses IPC). */
  has_password?: boolean;
  /** Detected distribution ("ubuntu", "fedora", "windows", …); "" = unknown. */
  os?: string;
  /** ssh_proxies row id to tunnel through ("" = direct connection). */
  proxy_id?: string;
}

/** A saved proxy a server can connect through (password encrypted at rest). */
export interface SshProxy {
  id: string;
  name: string;
  kind: "http" | "socks5";
  host: string;
  port: number;
  username: string;
  /** Plaintext only when saving ("" keeps the stored one, "-" clears it); blank in listings. */
  password: string;
  has_password: boolean;
}

/** A reusable private-key credential (secrets encrypted at rest). */
export interface SshKey {
  id: string;
  name: string;
  /** Plaintext only when saving; blank in listings. */
  private_key: string;
  /** Plaintext only when saving; blank in listings. */
  passphrase: string;
  /** True when a key body is stored. */
  has_key: boolean;
  /** "SHA256:…" of the stored key — for display only. */
  fingerprint: string;
  /** OpenSSH comment; "Generated By Singularity" on app-generated keys. */
  comment?: string;
  /** Public half (authorized_keys form) — safe to show/copy. */
  public_key?: string;
}

/** Detected server OS tokens → logo files in /icons/os ("" = no logo). */
export const OS_ICONS: Record<string, string> = {
  ubuntu: "/icons/os/ubuntu.png",
  debian: "/icons/os/debian.png",
  fedora: "/icons/os/fedora.png",
  redhat: "/icons/os/redhat.png",
  arch: "/icons/os/arch.png",
  windows: "/icons/os/windows.png",
  // Logo set has no macos file yet; the token is still recognized by Rust.
  macos: "",
};

/** A saved remote command the Units page runs with one click. */
export interface SshScript {
  id: string;
  name: string;
  description: string;
  content: string;
}

/**
 * One open SSH connection page — the Connections section of the sidebar.
 * A server can have several: each terminal click opens a NEW session
 * (like Termius tabs), and every SFTP browser page is its own entry too.
 */
export interface SshConn {
  /** Unique id of this connection page. */
  id: string;
  serverId: string;
  /** terminal = PTY console page, sftp = Files page. */
  kind: "terminal" | "sftp";
  /** Live PTY session id once the shell is open (terminal only). */
  sessionId?: string;
}

/** One SFTP directory entry. */
export interface SftpEntry {
  name: string;
  path: string;
  isDir: boolean;
  size: number;
  /** Unix seconds; 0 when unknown. */
  modified: number;
}

/** One audit row of the Logs page: who connected when, and how it ended. */
export interface SshLog {
  id: string;
  /** "user" — you, via the UI; "agent" — a model through the ssh_exec tool. */
  actor: string;
  server_id: string;
  server_name: string;
  host: string;
  /** "connect" | "disconnect" | "exec" | "shell" | "sftp-upload" | "sftp-download" */
  action: string;
  ok: boolean;
  detail: string;
  /** Unix seconds. */
  created_at: number;
}

export type ProviderKind =
  | "google"
  | "openai"
  | "openai-compatible"
  | "ollama"
  | "openai-completions"
  | "openai-responses"
  | "anthropic-messages"
  /* Subscription sign-in through the vendor's CLI, run headless by Rust. */
  | "openai-cli"
  | "anthropic-cli"
  | "google-cli";

/** Provider kinds that authenticate through a vendor CLI (Codex, Claude Code, Antigravity CLI). */
export const CLI_KINDS: ProviderKind[] = ["openai-cli", "anthropic-cli", "google-cli"];

export function isCliKind(kind: ProviderKind): boolean {
  return CLI_KINDS.includes(kind);
}

export type ProviderStatus = "ready" | "disconnected" | "error" | "checking";

/** Reasoning effort requested from the model, where the provider supports it. */
export type Effort = "low" | "medium" | "high" | "xhigh" | "max" | "ultra" | "ultracode";

export const EFFORTS: Effort[] = ["low", "medium", "high", "xhigh", "max", "ultra", "ultracode"];

/**
 * Effort levels a model accepts, lowest first. The provider sets the range:
 * OpenAI (Codex) adds Extra High and Ultra; Anthropic (Claude Code) adds Extra, Max and
 * Ultracode; Google (Antigravity), Ollama and API endpoints stop at High.
 * A subscription model's meta can narrow it to what that model has
 * (`subscription;efforts=low,high`; an empty list = the model takes none).
 */
export function effortsFor(kind?: ProviderKind, meta?: string): Effort[] {
  const range: Effort[] =
    kind === "openai-cli"
      ? ["low", "medium", "high", "xhigh", "ultra"]
      : kind === "anthropic-cli"
        ? ["low", "medium", "high", "xhigh", "max", "ultracode"]
        : ["low", "medium", "high"];
  const listed = /(?:^|;)efforts=([^;]*)/.exec(meta ?? "");
  if (!listed) return range;
  const own = listed[1].split(",");
  return range.filter((l) => own.includes(l));
}

/**
 * The user's pick for this model: kept when the model has it, else the
 * nearest level it has (ties go up). A model with no levels keeps the pick.
 */
export function clampEffort(effort: Effort, kind?: ProviderKind, meta?: string): Effort {
  const levels = effortsFor(kind, meta);
  if (levels.length === 0 || levels.includes(effort)) return effort;
  const rank = (l: Effort) => EFFORTS.indexOf(l);
  const dist = (l: Effort) => Math.abs(rank(l) - rank(effort));
  return levels.reduce((best, l) => (dist(l) < dist(best) || (dist(l) === dist(best) && rank(l) > rank(best)) ? l : best));
}

/** A file or image the user attached to a prompt. */
export interface Attachment {
  /** Stable id, used as the React key and for removal. */
  id: string;
  name: string;
  /** `image` renders as a preview, `text` is inlined into the prompt. */
  kind: "image" | "text";
  /** Media type, e.g. `image/png` or `text/plain`. */
  mime: string;
  /** Data URL for images, raw text for text files. */
  data: string;
  /** Size in bytes, for the chip label. */
  size: number;
}

/** A configured model provider (credentials + endpoint) — persisted in SQLite. */
export interface Provider {
  id: string;
  name: string;
  kind: ProviderKind;
  base_url: string;
  api_key: string;
  enabled: boolean;
  status: ProviderStatus;
  last_sync: number | null;
  /** "key" = API key, "bearer" = OAuth access token obtained by signing in. */
  auth: "key" | "bearer";
  /** Max requests per minute; 0 = no limit. Enforced in Rust before each call. */
  rate_limit_rpm: number;
  /** Max parallel in-flight requests; 0 = no limit. */
  concurrency: number;
}

/** Stored OAuth credentials for a provider (Google sign-in). */
export interface OAuthTokens {
  provider_id: string;
  access_token: string;
  refresh_token: string;
  /** Unix seconds. */
  expires_at: number;
  email: string;
  scope: string;
}

/** A single selectable model belonging to a provider. */
export interface Model {
  id: string;
  provider_id: string;
  model_id: string;
  name: string;
  meta: string;
  enabled: boolean;
}

/**
 * Humanizes a model id for display: `claude-fable-5` → `Claude Fable 5`.
 *
 * Dashes and slashes become spaces and each word is capitalized, but DOTS are
 * kept so version numbers stay intact: `gpt-4.1` → `Gpt 4.1`, never
 * `Gpt 4 1`. Ids that already look human (they contain a space) pass through
 * untouched, so a user's custom display name survives.
 */
/**
 * Stable model order for every list: grouped by family (the first word),
 * Gemini → Claude → GPT → the rest; inside a family by line (all Opus, then
 * all Sonnet…; plain GPT, then Codex, then mini), the newest version first
 * inside a line (Opus 5.5 above Opus 5), then by name. Catalogs arrive in whatever order
 * the provider or CLI prints them; this keeps lists from reshuffling.
 */
/** Family order: Gemini, then Claude (incl. Claude Code's Opus / Sonnet /
 *  Haiku aliases), then GPT, then everything else alphabetically. */
function familyRank(family: string): number {
  if (family === "gemini") return 0;
  if (["claude", "opus", "sonnet", "haiku", "fable"].includes(family)) return 1;
  if (family === "gpt" || /^(o\d|chatgpt|codex)/.test(family)) return 2;
  return 3;
}

/** Model lines inside a family, top tier first: all Opus above all Sonnet,
 *  plain GPT above Codex above mini… Unknown lines follow, alphabetically. */
const LINE_ORDER = ["", "opus", "pro", "sonnet", "codex", "fable", "flash", "haiku", "flash lite", "mini", "nano"];

function lineRank(line: string): number {
  const i = LINE_ORDER.indexOf(line);
  return i < 0 ? LINE_ORDER.length : i;
}

export function compareModels(a: string, b: string): number {
  const parse = (name: string) => {
    const n = name.toLowerCase().trim();
    const words = n.replace(/\(.*?\)/g, " ").split(/[\s\-_/:]+/).filter(Boolean);
    const family = words[0] ?? "";
    // First standalone version number: "gpt-5.6-sol" → 5.6, "gpt-oss-120b" → none.
    const v = /(?:^|[\s\-_])v?(\d+(?:\.\d+)*)(?=$|[\s\-_])/.exec(n);
    // The line: the words left without family, version and dates —
    // "Claude Opus 5.5" → "opus", "gpt-5.5-codex" → "codex", "GPT-6" → "".
    // Claude Code's bare aliases ("Opus (latest)") are their own line.
    const line = ["opus", "sonnet", "haiku", "fable"].includes(family)
      ? family
      : words.slice(1).filter((w) => !/^v?\d+(\.\d+)*$/.test(w)).join(" ");
    return { n, family, line, version: v ? v[1].split(".").map(Number) : null };
  };
  const x = parse(a);
  const y = parse(b);
  const rx = familyRank(x.family);
  const ry = familyRank(y.family);
  if (rx !== ry) return rx - ry;
  if (x.family !== y.family && !(rx === 1 && ry === 1)) return x.family.localeCompare(y.family);
  const lx = lineRank(x.line);
  const ly = lineRank(y.line);
  if (lx !== ly) return lx - ly;
  if (x.line !== y.line) return x.line.localeCompare(y.line);
  if (x.version && y.version) {
    for (let i = 0; i < Math.max(x.version.length, y.version.length); i++) {
      const d = (y.version[i] ?? 0) - (x.version[i] ?? 0);
      if (d !== 0) return d;
    }
  } else if (x.version || y.version) {
    return x.version ? -1 : 1;
  }
  return x.n.localeCompare(y.n, undefined, { numeric: true });
}

export function prettyModelName(id: string): string {
  if (!id) return id;
  if (id.includes(" ")) return id;
  const words = id
    .replace(/[/:@]/g, " ")
    .split(/[-_]+/)
    .filter(Boolean);
  return words
    .map((w) => (/^\d/.test(w) ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ");
}

/** Provider plus its models, in the shape the picker needs. */
export interface Gateway {
  id: string;
  name: string;
  kind: ProviderKind;
  status: ProviderStatus;
  enabled: boolean;
  models: Array<{ id: string; name: string; meta: string }>;
}

export interface StoredMessage {
  conversation_id: string;
  role: "user" | "agent" | "compact";
  text: string;
  created_at: number;
  /** How long the model spent producing this turn (agent messages only). */
  duration_ms?: number;
  /** JSON array of `{name, mime, data_url}` image attachments. */
  images?: string;
  /**
   * JSON array of the turn's interleaved segments (text / think / step) —
   * migration 9. Restoring them is what keeps tool-call cards, their outputs
   * and panel tabs alive after a restart.
   */
  segments?: string;
}

/** An image stored with a message, ready to render again after a reload. */
export interface StoredImage {
  name: string;
  mime: string;
  data_url: string;
}

/** Pseudo-project holding chats that belong to no folder. */
export const NO_PROJECT = "No project";

/** How many conversations a project shows before "See all (N)". */
export const CONV_LIMIT = 6;

/* ---------- Provider catalogue ---------- */

export interface ProviderTemplate {
  kind: ProviderKind;
  label: string;
  /** Default API root, pre-filled when adding the provider. */
  base_url: string;
  hint: string;
  /** Whether the user must supply an API key. */
  needsKey: boolean;
  /** Local providers are reachable without credentials. */
  local?: boolean;
}

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
  {
    kind: "openai-cli",
    label: "OpenAI",
    base_url: "",
    hint: "Sign in with your ChatGPT account. Runs through the Codex CLI in the background — downloaded automatically.",
    needsKey: false,
  },
  {
    kind: "anthropic-cli",
    label: "Anthropic",
    base_url: "",
    hint: "Sign in with your Claude account. Runs through Claude Code in the background — downloaded automatically.",
    needsKey: false,
  },
  {
    kind: "google-cli",
    label: "Google",
    base_url: "",
    hint: "Sign in with your Google account. Runs through the Antigravity CLI in the background — downloaded automatically.",
    needsKey: false,
  },
  {
    kind: "google",
    label: "Google Antigravity",
    base_url: "https://generativelanguage.googleapis.com",
    hint: "Gemini models. Sign in with your Google account or paste an AI Studio API key.",
    needsKey: false,
  },
  {
    kind: "openai-completions",
    label: "OpenAI Completions",
    base_url: "https://api.openai.com/v1",
    hint: "POST /chat/completions with stream — OpenAI, DeepSeek, OpenRouter, LM Studio, vLLM.",
    needsKey: true,
  },
  {
    kind: "openai-responses",
    label: "OpenAI Responses",
    base_url: "https://api.openai.com/v1",
    hint: "POST /responses with stream — the newer OpenAI protocol.",
    needsKey: true,
  },
  {
    kind: "anthropic-messages",
    label: "Anthropic Messages",
    base_url: "https://api.anthropic.com/v1",
    hint: "POST /messages with stream — Claude models.",
    needsKey: true,
  },
  {
    kind: "ollama",
    label: "Ollama (local)",
    base_url: "http://localhost:11434",
    hint: "Models served by a local Ollama instance. No API key required.",
    needsKey: false,
    local: true,
  },
];

/* ---------- OAuth client notes ---------- */

/**
 * Sign-in with a Google account only works with the user's own OAuth client.
 *
 * There is no usable built-in fallback: Google refuses third-party apps that
 * authenticate with its subscription clients (Gemini CLI / Antigravity) —
 * verified live against `cloudcode-pa`, which answers SUBSCRIPTION_REQUIRED /
 * UNSUPPORTED_CLIENT for them. The client ID therefore comes from the user's
 * Cloud Console, created as a "Desktop app" in a project where the Generative
 * Language API is enabled.
 */

/** Metadata for the theme dropdown: display label, kind and preview swatches. */
export interface ThemeMeta {
  id: Theme;
  label: string;
  kind: "dark" | "light";
  /** [background, surface, accent] — rendered as dots in the picker. */
  swatch: [string, string, string];
}

export const THEME_LIST: ThemeMeta[] = [
  { id: "dark", label: "Dark", kind: "dark", swatch: ["#101010", "#1c1c1c", "#388BFD"] },
  { id: "light", label: "Light", kind: "light", swatch: ["#F8F9FA", "#FFFFFF", "#0969DA"] },
  { id: "slate", label: "Slate", kind: "dark", swatch: ["#0F172A", "#1E293B", "#0EA5E9"] },
  { id: "amoled", label: "AMOLED Black", kind: "dark", swatch: ["#000000", "#111111", "#3B82F6"] },
  { id: "one-dark-pro", label: "One Dark Pro", kind: "dark", swatch: ["#21252B", "#282C34", "#61AFEF"] },
  { id: "dracula", label: "Dracula", kind: "dark", swatch: ["#21222C", "#282A36", "#BD93F9"] },
  { id: "github-dark", label: "GitHub Dark", kind: "dark", swatch: ["#010409", "#0D1117", "#2F81F7"] },
  { id: "github-light", label: "GitHub Light", kind: "light", swatch: ["#F6F8FA", "#FFFFFF", "#0969DA"] },
  { id: "tokyo-night", label: "Tokyo Night", kind: "dark", swatch: ["#16161E", "#1A1B26", "#7AA2F7"] },
  { id: "monokai-pro", label: "Monokai Pro", kind: "dark", swatch: ["#19181A", "#2D2A2E", "#FFD866"] },
  { id: "solarized-dark", label: "Solarized Dark", kind: "dark", swatch: ["#00212B", "#002B36", "#268BD2"] },
  { id: "solarized-light", label: "Solarized Light", kind: "light", swatch: ["#EAE3CB", "#FDF6E3", "#268BD2"] },
  { id: "nord", label: "Nord", kind: "dark", swatch: ["#242933", "#2E3440", "#88C0D0"] },
  { id: "gruvbox", label: "Gruvbox Dark", kind: "dark", swatch: ["#1D2021", "#282828", "#FABD2F"] },
  { id: "catppuccin", label: "Catppuccin Mocha", kind: "dark", swatch: ["#11111B", "#1E1E2E", "#89B4FA"] },
  { id: "vibe", label: "Synthwave", kind: "dark", swatch: ["#12081F", "#221039", "#FF5AC5"] },
];

/** Every theme the app ships with — Settings → General lists these. */
export const THEMES: Theme[] = THEME_LIST.map((t) => t.id);

/** A recurring agent job (Scheduled Tasks page). */
export interface ScheduledTask {
  id: string;
  name: string;
  /** Project the new chat is created in (required). */
  project: string;
  provider_id: string;
  model_id: string;
  /** Which editor built `schedule` — presets are stored as cron too. */
  kind: "hourly" | "daily" | "weekly" | "cron";
  /** 5-field cron expression, local time. */
  schedule: string;
  prompt: string;
  enabled: boolean;
  /** Unix seconds of the last run; null = never ran. */
  last_run_at: number | null;
  /** The schedule counts from here (last run, save or resume), unix seconds. */
  armed_at: number;
  /** Conversation the last run created ("" = none yet). */
  last_conv: string;
  created_at: number;
}
